name: multitenant-app

tenantHeader: X-TENANT-ID

tenants:
  - id: tenant1
    databases:
      hibernate:
        driverClass: com.mysql.cj.jdbc.Driver
        user: hmbuser
        password: hmbpasswd
        url: jdbc:mysql://localhost:3306/tenant1?autoReconnect=true&useSSL=false&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=false
        properties:
          charSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true
          hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          hibernate.show_sql: true
          hibernate.generate_statistics: false
          hibernate.hbm2ddl.auto: create
          hibernate.jdbc.time_zone: UTC

        maxWaitForConnection: 1s
        validationQuery: "SELECT 1"
        minSize: 8
        maxSize: 32
        checkConnectionWhileIdle: true
        checkConnectionOnBorrow: true
        checkConnectionOnConnect: true
        checkConnectionOnReturn: true
  - id: tenant2
    databases:
      hibernate:
        driverClass: com.mysql.cj.jdbc.Driver
        user: hmbuser
        password: hmbpasswd
        url: jdbc:mysql://localhost:3306/tenant2?autoReconnect=true&useSSL=false&nullNamePatternMatchesAll=true&useLegacyDatetimeCode=false
        properties:
          charSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true
          hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          hibernate.show_sql: true
          hibernate.generate_statistics: false
          hibernate.hbm2ddl.auto: create
          hibernate.jdbc.time_zone: UTC

        maxWaitForConnection: 1s
        validationQuery: "SELECT 1"
        minSize: 8
        maxSize: 32
        checkConnectionWhileIdle: true
        checkConnectionOnBorrow: true
        checkConnectionOnConnect: true
        checkConnectionOnReturn: true

logging:
  level: INFO
  loggers:
    "io.dropwizard": DEBUG
    "org.hibernate.SQL":
      level: DEBUG
      additive: false
      appenders:
        - type: console
  appenders:
    - type: console